### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MBeijer** [AmigaPorts/docker-amiga-gcc#10]
I would like to change the licence of this repository to MPL and apply the MPL license to the AmigaCMakeCrossToolchains repository as well. Anyone opposing?

**Comment by tehKaiN** [comment]
YES!

**Comment by apiraino** [comment]
Reasons to switch from the GPL?

I'm quickly skimming [this stackoverflow answer](https://opensource.stackexchange.com/questions/8831/pros-and-cons-of-using-mpl-2-0-license) and it seems that changing to the MPL 2.0 implies putting a disclaimer about the license in each file? 

(didn't look at it deeper though)

**Comment by MBeijer** [comment]
@apiraino GPL is a bit restrictive, and is a viral license format. MPL is somewhere in between MIT and GPL, and doesn't require anyone that includes this in their project to use the same license.

MPL has a lot in common with APL (AROS Public License), which I'm pretty sure is based on MPL.

**Comment by MBeijer** [comment]
Of course, adding the license header now is of course the next step if the license change is approved by all contributors.
