### ISSUE TITLE
GCC disappeared

### ISSUE THREAD

**Issue by sodero** [AmigaPorts/docker-amiga-gcc#2]
It seems that your latest changes made GCC go away:

olasr@lnxolasr1:~/kod/amiga/MUI-Vim$ docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos bash 
root@beba161d9154:/work# which ppc-morphos-gcc
root@beba161d9154:/work# echo $?
1

olasr@lnxolasr1:~/kod/amiga/MUI-Vim$ docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-amigaos bash 
root@9660f0f5ab61:/work# which ppc-amigaos-gcc
root@9660f0f5ab61:/work# echo $?
1

**Comment by sodero** [comment]
Great job otherwise BTW, really useful.

**Comment by MBeijer** [comment]
@sodero This happened due to a typo! Thanks for notifying me about this! Latest commit will fix it, but it will take a while until it's properly built

**Comment by MBeijer** [comment]
I'm happy to see people are actually using the crosstools docker image! =)
